### ISSUE TITLE
What is the difference from simple-vars?

### ISSUE THREAD

**Issue by hudochenkov** [jonathantneal/postcss-advanced-variables#1]
How this plugin is different from [postcss-simple-vars](https://github.com/postcss/postcss-simple-vars)?

**Comment by gillchristian** [comment]
@hudochenkov someone correctme if I'm wrong, but this plugin also adds some SASS-like conditionals.

**Comment by jonathantneal** [comment]
Right now, advanced variables is required, because computation of variables must happen alongside Sass-like conditionals.
