### ISSUE TITLE
Add support for scss variable default statement

### ISSUE THREAD

**Issue by soilysound** [jonathantneal/postcss-advanced-variables#12]
Scss can do this with variables - 

```
$example: 'value' !default;
```

Whereby it will only set the value of $example if it doesn't already exist. This is an important function to allow cascading. 

Could this be supported in postcss-advanced-variables ?

**Comment by mjschlot** [comment]
Isn't this already supported? I could swear I have used it recently. And, here see line 12 of:
https://github.com/jonathantneal/postcss-advanced-variables/blob/master/index.js

**Comment by contentjet** [comment]
Assuming @mjschlot is correct and it does work, @jonathantneal can we get this added to the README please?

**Comment by 1j01** [comment]
This does indeed appear to work. I'd prefer the syntax `$example?: 'value';` which would jive with CoffeeScript's `?=`, but this feature should definitely be documented regardless.

**Comment by jonathantneal** [comment]
This has been available to the plugin. And there are tests to ensure its functionality.
