### ISSUE TITLE
list support is unclear

### ISSUE THREAD

**Issue by Lokua** [jonathantneal/postcss-advanced-variables#19]
I came here via precss, so forgive me if this isn't the correct place to bring this up.

I don't see any mention of lists in the readme, aside from the `@each` example. I'm not sure if this is a feature of postcss-advanced-variables or just luck or what, but this is what I've found:

``` css
// this works with @each
$list: foo, bar;

// this too
$list: (foo, bar);

// and so do these
$list:
  foo,
  bar;

$list: foo,
  bar;

// but this results in looping though each character
$list: (
  foo,
  bar
);
```

The last way was the first I tried from intuition, but that's just me. In any case I would have benefited from some documentation, especially being that list support is totally a feature worth noting!

**Comment by jonathantneal** [comment]
Thanks for pointing this out. Those should all work now, but do raise an issue if they do not, or add a PR if you think more documentation would be helpful. Otherwise, the Sass docs will manage this.
