### ISSUE TITLE
not all support selector variable

### ISSUE THREAD

**Issue by xiaoDC** [jonathantneal/postcss-advanced-variables#21]
I have a example

$selectPrefixCls: rc-select;
.search__field__wrap-$selectPrefixCls {
     width: 100%;
  }

can compile to 
.search__field__wrap-rc-select {
     width: 100%;
  }

but when i wirte it like this
$selectPrefixCls: rc-select;
.$selectPrefixCls-search__field__wrap {
     width: 100%;
  }
it can not compile to

.rc-select-search__field__wrap {
     width: 100%;
  }

**Comment by jonathantneal** [comment]
This is because you needed to wrap your variable name, like `$(selectPrefixCls)-search__field__wrap`.
