### ISSUE TITLE
Only first variable interpolated when variables not separated with other chars

### ISSUE THREAD

**Issue by kommen** [jonathantneal/postcss-advanced-variables#26]
Interpolation of variables not separated with some character only replaces the first variable.

See my failing test case here: https://github.com/kommen/postcss-advanced-variables/commit/3a748e18085259a11aba89fb2f35b5e87b45a1df

**Comment by tortilaman** [comment]
For me when I had variables with dashes in the name it would only replace the first instance.

**Comment by jonathantneal** [comment]
This is now supported in v2.0.0
