### ISSUE TITLE
warn if undefined variable is used

### ISSUE THREAD

**Issue by itajaja** [jonathantneal/postcss-advanced-variables#28]
an undefined variable is silently copied through. Is there a way to fail or show warnings? Many times an undefined variable is a just a typo

**Comment by am80l** [comment]
Just found a variable that has been in our output for months due to this issue. postcss-simple-variables supports a silent : true/false option. We will be switching to that project until this feature is supported.

**Comment by mjschlot** [comment]
I have completed the upgrade and submitted a pull request:
https://github.com/jonathantneal/postcss-advanced-variables/pull/37

**Comment by jonathantneal** [comment]
This is in 2.0.0. Happy New Year! https://github.com/jonathantneal/postcss-advanced-variables/blob/master/CHANGELOG.md#200-december-31-2017
