### ISSUE TITLE
importing variables from another module

### ISSUE THREAD

**Issue by itajaja** [jonathantneal/postcss-advanced-variables#29]
Is it possible to have a variable imported from a different css file?

**Comment by alferov** [comment]
https://github.com/jonathantneal/postcss-advanced-variables#variables
You could make these variables global and share them within your project (and store them in a json file, for example)

```js
require('postcss-advanced-variables')({
    variables: require('./path/to/your/json')
});
```

Probably, [postcss-partial-import](https://github.com/jonathantneal/postcss-partial-import) could be helpfull as well.

**Comment by jonathantneal** [comment]
Yes, you can import variables from another file using PostCSS Import, but you can also import them from the new `variables` option, which supports passing them as either an object or a function.
