### ISSUE TITLE
passing variables to start, end and increment params

### ISSUE THREAD

**Issue by etanlubeck** [jonathantneal/postcss-advanced-variables#3]
I think it would be helpful to add support for passing variables to start, end and increment properties.

example: 
```
@for $i from $start to $end by $increment {}

```

**Comment by jonathantneal** [comment]
It is helpful, and [you can](https://jonathantneal.github.io/precss/#$start:+1;%0A$end:+10;%0A$incrememt:+1;%0A%0A@for+$i+from+$start+to+$end+by+$increment+%7B%0A%09.col-$i+%7B%7D%0A%7D)! Please me know if you were expecting something different.

**Comment by etanlubeck** [comment]
I'll try that. I passed them in as arguments of a mixin and didn't work. I'll check my syntax.
