### ISSUE TITLE
fix numbers comparison in @if

### ISSUE THREAD

**Issue by vsubbotskyy** [jonathantneal/postcss-advanced-variables#32]
Today I encountered interesting case. Took me quite some time to figure it out.
```
@for $i from 0 to 10 {
        @if $i < 50 {
                  //true
        }
        @else {
                  //false
        }
}
```
result was surprising when left operand equals 6, 7, 8 or 9:
$i == 1 => true
$i == 2 => true
$i == 3 => true
$i == 4 => true
$i == 5 => true
$i == 6 => false
$i == 7 => false
$i == 8 => false
$i == 9 => false
$i == 10 => true

turned out, it compares strings which are compared lexicographically

**Comment by vsubbotskyy** [comment]
I created a PR to address this issue
#33

**Comment by jonathantneal** [comment]
Merged https://github.com/jonathantneal/postcss-advanced-variables/pull/33
