### ISSUE TITLE
'@csstools/sass-import-resolve' is not in the npm registry.

### ISSUE THREAD

**Issue by jwkellyiii** [jonathantneal/postcss-advanced-variables#43]
Unable to install https://github.com/jonathantneal/precss due to https://github.com/jonathantneal/postcss-advanced-variables and its dependency on `@csstools/sass-import-resolve`. Getting `@csstools/sass-import-resolve` is not in the npm registry.

Added `@csstools/sass-import-resolve:registry = "http://registry.npmjs.org"` to my npm config to no avail.

Trying to upgrade from precss 2.0.0 to 3.1.0

**Comment by jonathantneal** [comment]
Are you able to see this? https://www.npmjs.com/package/@csstools/sass-import-resolve

**Comment by jwkellyiii** [comment]
Yep.

**Comment by jonathantneal** [comment]
What happens when you follow their instructions in your terminal?

```
npm i @csstools/sass-import-resolve
```

Does the name differ from https://github.com/jonathantneal/postcss-advanced-variables/blob/master/package.json#L29 ?

If it does not, this sounds like an NPM bug. Would you confirm?

**Comment by jwkellyiii** [comment]
npm ERR! 404 no such package available : @csstools/sass-import-resolve
npm ERR! 404
npm ERR! 404  '@csstools/sass-import-resolve' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Comment by jonathantneal** [comment]
@jwkellyiii, it seems either the npm registry is not functioning correctly, or you have an issue on your end with the npm registry. Are you already customizing your npm registry?

**Comment by jwkellyiii** [comment]
Had to add `@csstools` to my npm config via `npm config set @csstools:registry http://registry.npmjs.org` 

Now working. Might want to add a note to the README....

**Comment by jonathantneal** [comment]
@jwkellyiii, I would, but you’re the first person to experience this issue, and we wouldn’t want to make everyone run such a command every time they go to install a scoped dependency, like, say https://github.com/babel/babel/tree/master/packages/babel-preset-env

I’m still interested in resolving that root issue. How are you customizing your npm config?

**Comment by jwkellyiii** [comment]
We have an internal (private) company registry. So anything prefixed (i.e. `@csstools`, `@storybook`, `@webpack-blocks`) needs to be added to the config via `npm config set ...`

**Comment by jonathantneal** [comment]
@jwkellyiii, thanks for the details, because that might help similar users in the future.

And, in your case, I recommend your company wiki gets that important info :) Glad it was resolved quickly!
