### ISSUE TITLE
Shouldn't include `require('babel-polyfill');`

### ISSUE THREAD

**Issue by dylang** [jonathantneal/postcss-advanced-variables#45]
https://github.com/jonathantneal/postcss-advanced-variables/blob/master/index.js#L2

This probably shouldn't be in the distributed bundle, because it Babel throws an error if it's already included, and it means this library can't be imported into in any projects that are already using `babel-polyfill`.

Thanks!

**Comment by jonathantneal** [comment]
Thank you for reporting this! It is fixed in v2.3.1.
