### ISSUE TITLE
`@mixin foo() {...}` causes error due to empty arg brackets

### ISSUE THREAD

**Issue by Knagis** [jonathantneal/postcss-advanced-variables#47]
This throws:

```
@mixin foo() {
  color: red;
}
```

> TypeError: Cannot read property 'slice' of undefined
>     at node_modules\postcss-advanced-variables\index.bundle.js:608:27
>     at Array.map (<anonymous>)
>     at getMixinOpts (node_modules\postcss-advanced-variables\index.bundle.js:606:76)
>     at transformMixinAtrule (node_modules\postcss-advanced-variables\index.bundle.js:584:23)
>     at node_modules\postcss-advanced-variables\index.bundle.js:691:5
>     at Array.forEach (<anonymous>)
>     at transformNode (node_modules\postcss-advanced-variables\index.bundle.js:666:22)
>     at node_modules\postcss-advanced-variables\index.bundle.js:738:3
>     at LazyResult.run (node_modules\postcss\lib\lazy-result.js:277:20)
>     at LazyResult.asyncTick (node_modules\postcss\lib\lazy-result.js:192:32)
> error Command failed with exit code 1.

While this works:

```
@mixin foo {
  color: red;
}
```

**Comment by jonathantneal** [comment]
Thank you for reporting this! It is fixed in v2.3.1.
