### ISSUE TITLE
Unable to import mixins/variables

### ISSUE THREAD

**Issue by TehShrike** [jonathantneal/postcss-advanced-variables#51]
Using postcss-advanced-variables 2.1.x, I'm not able to define a mixin or a variable in one file, and then import that file to use the mixin/variable in another file.

Failing tests coming momentarily.

**Comment by TehShrike** [comment]
Sorry for the bump, but any chance you could cut a release soon? 🥑

**Comment by jonathantneal** [comment]
Done.
