### ISSUE TITLE
Unable to sum breakpoint variables

### ISSUE THREAD

**Issue by lhguerra** [jonathantneal/postcss-advanced-variables#73]
In SASS I am able to do things like this:
```
$breakpointSm: 480px;
$breakpointMd: 600px;

$breakpointMdMin: $breakpointSm + 1;
```

This way, my `$breakpointMdMin` var will be translated to `481px` in SASS, but to `480px + 1` with this package.

**Comment by lhguerra** [comment]
Here's an example: https://www.sassmeister.com/gist/e0297b699080e1ea6da7903d6f739b20

**Comment by MaxMilton** [comment]
The scope of this plugin is a bit more limited than what you seem to be expecting. If the functionality isn't described in the readme or unit tests then it's likely not supported.

To support arithmetic operators I suggest having a look at the [postcss-calc plugin](https://github.com/postcss/postcss-calc). You'll then be able to write:

```scss
$breakpointSm: 480px;
$breakpointMd: 600px;

$breakpointMdMin: calc($breakpointSm + 1);
```

which would then be evaluated at build time and reduced to the correct value.

If you're using something like [cssnano](https://cssnano.co/) then it already includes `postcss-calc` and you won't need to explicitly add it to your PostCSS plugin stack.

**Comment by lhguerra** [comment]
@MaxMilton thanks, that makes sense. I think we can close this issue then.
