### ISSUE TITLE
Need (@else if) and boolean variable support

### ISSUE THREAD

**Issue by asifshirazi** [jonathantneal/postcss-advanced-variables#8]
I'm converting my sass mixins library into postcss, but not possible yet:

    @define-mixin center $horizontal: true, $vertical: true {
        position: absolute;
        @if $horizontal || $vertical {
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        } @else if $horizontal {
            left: 50%;
            transform: translate(-50%, 0);
        } @else if $vertical {
            top: 50%;
            transform: translate(0, -50%);
        }
    }

**Comment by etanlubeck** [comment]
@asifshirazi I have a pr that will fix this. It has to do with the order in which the processors are called.

**Comment by jonathantneal** [comment]
@etanlubeck were you going to make the PR?

**Comment by etanlubeck** [comment]
I fixed this one in a different PR that we closed

**Comment by jonathantneal** [comment]
So we now have `@else` support? What about boolean?

**Comment by etanlubeck** [comment]
nvm. i just looked at the example. we should re-open this issue. i'll submit a PR this evening after work.

**Comment by jonathantneal** [comment]
I think we support `@else` but not boolean, so did you want to make a PR or shall we close this issue, and you could open one for boolean support?

**Comment by jonathantneal** [comment]
We have `else` support so I am closing this. Feel free to re-open if you find something.
