### ISSUE TITLE
Publish release

### ISSUE THREAD

**Issue by MaxMilton** [jonathantneal/postcss-advanced-variables#84]
It's been almost a year since https://github.com/jonathantneal/postcss-advanced-variables/pull/71 was merged... but we haven't seen a release yet. I've been installing from my Github for a long time but I've seen the issue described in https://github.com/jonathantneal/postcss-advanced-variables/issues/70 poping up in other projects too so it would be great for everyone to benefit from the fix.

A patch release is all we need e.g., `3.0.1` :smiley_cat:

**Comment by jonathantneal** [comment]
You asked the right day. I’m on it.

I’m getting on these as they pop up today. I know it’s coincidence, but today it’s like someone figured out that I’m responding, and kind folks (like you) are helping me find these neglects.

**Comment by jonathantneal** [comment]
Published! https://www.npmjs.com/package/postcss-advanced-variables/v/3.0.1

**Comment by MaxMilton** [comment]
Thank you very much :100:
