### ISSUE TITLE
Node#removeSelf Warning

### ISSUE THREAD

**Issue by gillchristian** [jonathantneal/postcss-advanced-variables#9]
I'm got this *warning*: `Node#removeSelfe is deprecated. Use Node#remove` when using the plugin. There weren't any problems with the results. But wanted to share.

This is how I'm running it.

```
var gulp            = require('gulp'),
    postcss         = require('gulp-postcss'),
    variables       = require('postcss-advanced-variables');

gulp.task('test', function () {
    var processors = [
        variables
    ];
    return gulp.src('toCompile/test.css')
        .pipe( postcss(processors) )
        .pipe(gulp.dest(''))
});
```

I hope this is useful!

EDIT: it might not be caused by this plugin but by PostCSS itself, but I only get the *warning* when I use the plugin.

**Comment by jonathantneal** [comment]
Resolved by updating the API to PostCSS 5
